---
- name: create key pair
  ec2_key:
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    region: "{{ region }}"
    name: "{{ keyname }}"
  register: mykey

- name: write key to file
  copy: content="{{ mykey.key.private_key }}" dest="./{{ keyname }}.pem" mode=0600
  when: mykey.changed

- name: double-check that permissions are correct
  file:
   path: "./{{ keyname }}.pem"
   owner: root
   group: root
   mode: 0600

- name: copy key to .ssh dir
  copy:
   src: "./{{ keyname }}.pem"
   dest: /root/.ssh/
