---
- name: Create keypair, vpc, security group, deploy ec2
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2-key
    - vpc
    - sg
    - ec2-instances

- name: deploy frontend software
  hosts: frontend_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - frontend

- name: prepare playbook for teamcity
  hosts: localhost
  connection: local
  roles:
    - prepare

- name: display final installation information
  hosts: localhost
  connection: local
  tasks:
  - debug: msg="Installed instance available at http://{{ frontend_dns }} hostname"
  - debug: msg="Your SSH private key stored as {{ keyname }}.pem in working directory"
  - debug: msg="Written by Eldar Karazhas. Have a nice day!"
