---
- name: Create frontend ec2 instance
  ec2:
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    key_name: "{{ keyname }}"
    instance_type: "{{ instance_type }}"
    volumes:
       - device_name: '/dev/sda1'
         volume_size: 10
         delete_on_termination: true
    region: "{{ region }}"
    image: "{{ image }}"
    wait: yes
    vpc_subnet_id: "{{ (vpc_subnet_facts.subnets | selectattr('tags.Name','equalto','frontend_cidr') | first).id }}"
    assign_public_ip: yes
    instance_tags: { "Name":"eldar-frontend" }
    group: eldar-sg
  register: frontend

- name: set the facts for frontend host
  set_fact:
   frontend_dns: "{{ item.public_dns_name }}"
   frontend_ip: "{{ item.public_ip }}"
  with_items: "{{ frontend.instances }}"
  
- name: add frontend instance to in-memory inventory at runtime
  add_host: name="{{ item.public_ip }}" 
            groups=frontend_hosts
            ansible_python_interpreter=/usr/bin/python3
  with_items: "{{ frontend.instances }}"

- name: wait for SSH
  wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=320 state=started
  with_items: "{{ frontend.instances }}"  

- name: and wait little bit more
  raw: sleep 20
